content:
  - name: docs
    label: Dokümantasyon
    type: collection
    path: docs
    format: yaml-frontmatter

    fields:
      - name: title
        label: Başlık
        type: string

      - name: body
        label: İçerik
        type: rich-text


