content:
  root: content

collections:
  docs:
    label: Docs
    folder: content/docs
    create: true
    format: frontmatter
    fields:
      title:
        label: Title
        type: string
        required: true

      description:
        label: Description
        type: string
        required: false

      weight:
        label: Weight
        type: number
        required: false

      body:
        label: Content
        type: markdown
        required: true

