content:
  root: content

collections:
  docs:
    label: Docs
    folder: content/docs
    create: true
    format: frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: description
        label: Description
        type: string
        required: false

      - name: weight